services:
  nuxbill:
    container_name: nuxbill
    pull_policy: always
    build: ./
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      TZ: ${TZ:-UTC}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_SSL: ${DB_SSL:-false}
      DB_SSL_CA: ${DB_SSL_CA:-}
    env_file:
      - .env